"""last sent anecdote

Revision ID: 979a1be87c60
Revises: fc4e44152ec9
Create Date: 2025-06-14 21:55:29.097263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '979a1be87c60'
down_revision: Union[str, None] = 'fc4e44152ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anecdotes', sa.Column('last_sent', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anecdotes', 'last_sent')
    # ### end Alembic commands ###
